baseURL = "https://peakxu.github.io"
title = "Peak Xu"
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""
Paginate = 5

preserveTaxonomyNames = true

[params]
  description = "Peak Xu static site"
  dateFormat = "2006, Jan 2"
  copyrightOwner = "Peak Xu"
  copyrightStartYear = "2017"
  favicon = "favicon.ico"
  hideEntryNavigation = false
  customCSS = ["css/prism.css"]
  customJS = ["js/prism.js", "js/custom.js"]
  hideSocialMenu = false
  showReadTime = true

[params.seo]
  # Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "•"

[params.opengraph]
  [params.opengraph.facebook]
    admins = ""
    appid = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[social]
  facebook = "peak.xu"

[author]
  name = "Peak Xu"

[author.social]
  email = "peak.xu@gmail.com"
  facebook = "peak.xu"
  github = "peakxu"
  linkedin = "yuetian-peak-xu-444677b"

[permalinks]
  page = "/:slug/"

[[menu.main]]
  name = "Blog"
  weight = -70
  identifier = "peakxu"
  url = "https://peakxu.github.io"

# Language Configuration
defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
